apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-server
  template:
    metadata:
      labels:
        app: json-server
    spec:
      containers:
        - name: json-server
          image: registry10032025.azurecr.io/kebab:v2
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: json-server-service
spec:
  type: LoadBalancer
  selector:
    app: json-server
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 3000 
