name: Build Docker Image, Update GitOps, and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the current repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to Azure using the service principal credentials
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t json-server:$GITHUB_SHA .

      # Tag image with GitHub SHA
      - name: Tag Docker image
        run: |
          docker tag json-server:$GITHUB_SHA ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/json-server:$GITHUB_SHA

      # Log in to Azure Container Registry (ACR)
      - name: Azure Container Registry login
        run: |
          az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      # Push Docker image to ACR
      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/json-server:$GITHUB_SHA

      # Clone the GitOps repository
      - name: Clone GitOps repository
        uses: actions/checkout@v4
        with:
          repository: fabremartin/gitops
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops-repo

      # Check the content of the GitOps file before making changes
      - name: Check content before update
        run: |
          cat gitops-repo/json-server.yaml

      # Update GitOps manifest with new image tag
      - name: Update GitOps manifest with new image tag
        run: |
          sed -i "s|image: ${GITHUB_SHA}|image: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/json-server:$GITHUB_SHA|g" gitops-repo/json-server.yaml

      # Check the content after updating
      - name: Check content after update
        run: |
          cat gitops-repo/json-server.yaml

      # Commit and push updated GitOps manifest
      - name: Commit and push updated GitOps manifest
        run: |
          cd gitops-repo
          git config --global user.name "fabremartin"
          git config --global user.email "lucian.clain@gmail.com"
          git add json-server.yaml
          git diff --exit-code || git commit -m "Update Docker image tag to ${{ github.sha }}"
          git push origin main
