name: Build, Tag, and Deploy to AKS with FluxCD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Build Docker image and tag with GitHub SHA
      uses: azure/CLI@61bb69d64d613b52663984bf12d6bac8fd7b3cc8
      with:
        azcliversion: 2.29.1
        inlineScript: |
          az configure --defaults acr=${{ secrets.AZURE_CONTAINER_REGISTRY }} 
          az acr build --registry ${{ secrets.AZURE_CONTAINER_REGISTRY }} \
                       --image ${{ secrets.AZURE_CONTAINER_REGISTRY }}/json-server:${{ github.sha }} .

    - name: Clone GitOps repository
      uses: actions/checkout@v4
      with:
        repository: fabremartin/gitops
        token: ${{ secrets.GITOPS_PAT }}
        path: gitops-repo

    - name: Update GitOps manifest with new image tag
      run: |
        sed -i "s|image: ${REGISTRY}/json-server:.*|image: ${REGISTRY}/json-server:${GITHUB_SHA}|g" gitops-repo/json-server.yaml

    - name: Commit and push updated GitOps manifest
      run: |
        cd gitops-repo
        git config --global user.name "fabremartin" #
        git config --global user.email "lucian.clain@gmail.com"  #
        git add json-server.yaml
        git commit -m "Update Docker image tag to ${{ github.sha }}"
        git push origin main

    #- name: Reconcile with FluxCD
    #  run: |
    #    flux reconcile kustomization <your-kustomization-name> --namespace <flux-system-namespace>
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
